### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Neotras** [itpao25/ReporterGUI#1]
Deutsch:

kann man eventuell einfügen das spieler eine benutzer difinierte nachricht über das gui menü eingeben können zb das sich dann die amboss oberfläche öffent und sie dort den grund eingeben können?

Englisch:

eg can you can insert eventually the player a user difinierte object via the gui enter menu which then published the anvil surface and they can enter the ground there ?

google translation

**Comment by itpao25** [comment]
For the moment you can use the command reportcli `/reportcli <name player> <reason>` 
The idea of the use of an anvil It could be implemented in future versions

**Comment by Neotras** [comment]
nice thanks
