### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by PabloGamer380YT** [itpao25/ReporterGUI#5]
24.06 18:36:20 [Server] INFO PabloGamer380 issued server command: /report Sayan_PvP
24.06 18:36:22 [Server] WARN Plugin Unknown is performing a blocking action on the main thread. This could be a performance hit Socket: socket://158.69.54.54:3306. Such actions should be handled async from the main thread. Report it to the plugin author
24.06 18:36:22 [Server] WARN The following exception is not an error. It's a hint for the plugin developer to find the source of the threading action. LagMonitor doesn't prevent this action. It just warns you
24.06 18:36:22 [Server] INFO java.lang.IllegalAccessException
24.06 18:36:22 [Server] INFO at com.github.games647.lagmonitor.threading.BlockingActionManager.logCurrentStack(BlockingActionManager.java:55) [LagMonitor.jar:?]
24.06 18:36:22 [Server] INFO at com.github.games647.lagmonitor.threading.BlockingActionManager.checkBlockingAction(BlockingActionManager.java:42) [LagMonitor.jar:?]
24.06 18:36:22 [Server] INFO at com.github.games647.lagmonitor.listeners.BlockingConnectionSelector.select(BlockingConnectionSelector.java:27) [LagMonitor.jar:?]
24.06 18:36:22 [Server] INFO at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:384) [?:1.8.0_131]
24.06 18:36:22 [Server] INFO at java.net.Socket.connect(Socket.java:589) [?:1.8.0_131]
24.06 18:36:22 [Server] INFO at java.net.Socket.connect(Socket.java:538) [?:1.8.0_131]
24.06 18:36:22 [Server] INFO at java.net.Socket.<init>(Socket.java:434) [?:1.8.0_131]
24.06 18:36:22 [Server] INFO at java.net.Socket.<init>(Socket.java:244) [?:1.8.0_131]
24.06 18:36:22 [Server] INFO at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:254) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:292) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2334) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2186) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2168) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at sun.reflect.GeneratedConstructorAccessor42.newInstance(Unknown Source) [?:1.8.0_131]
24.06 18:36:22 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_131]
24.06 18:36:22 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_131]
24.06 18:36:22 [Server] INFO at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at java.sql.DriverManager.getConnection(DriverManager.java:664) [?:1.8.0_131]
24.06 18:36:22 [Server] INFO at java.sql.DriverManager.getConnection(DriverManager.java:208) [?:1.8.0_131]
24.06 18:36:22 [Server] INFO at it.itpao25.NMSReport.o.c.b(MysqlReport.java:106) [ReporterGUI%20(1).jar:?]
24.06 18:36:22 [Server] INFO at it.itpao25.NMSReport.o.c.a(MysqlReport.java:66) [ReporterGUI%20(1).jar:?]
24.06 18:36:22 [Server] INFO at it.itpao25.NMSReport.c.<init>(Segnalazione.java:118) [ReporterGUI%20(1).jar:?]
24.06 18:36:22 [Server] INFO at it.itpao25.NMSReport.f.b.<init>(ListenerSlot.java:83) [ReporterGUI%20(1).jar:?]
24.06 18:36:22 [Server] INFO at it.itpao25.NMSReport.f.d.a(openGUI.java:116) [ReporterGUI%20(1).jar:?]
24.06 18:36:22 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
24.06 18:36:22 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
24.06 18:36:22 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
24.06 18:36:22 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
24.06 18:36:22 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
24.06 18:36:22 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
24.06 18:36:22 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [my.jar:git-Spigot-76236cb-62a2169]
24.06 18:36:22 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by itpao25** [comment]
Can you post the log when the plugin is loaded?
